title: BHASKAR JAIN
author: Bhaskar Jain
email: jainbhaskar1003@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Thanks for visiting my site! 
  I hope you get to learn more about me through this. 
  Contact me if you have any questions or inquiries.

# social links
twitter_username: Bhaskar03631319 # DO NOT include the @ character, or else the build will fail!
github_username:  BhaskarJain1003 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
